### Print all employees
GET http://localhost:8080/employee
Accept: application/json

### Get all employees
GET http://localhost:8080/department/employees
Accept: application/json

### Print all employees by department ID
GET http://localhost:8080/department/{{id}}/employees
Accept: application/json

### Print total salary in department
GET http://localhost:8080/department/{{id}}/salary/sum
Accept: application/json

### Print max salary in department
GET http://localhost:8080/department/{{id}}/salary/max
Accept: application/json

### Print min salary in department
GET http://localhost:8080/department/{{id}}/salary/min
Accept: application/json

### Print an employee with max salary
GET http://localhost:8080/employee/max-salary
Accept: application/json

### Print total monthly salary
GET http://localhost:8080/employee/total-salary
Accept: application/json

### Add Ivan Ivanov Dprt1
GET http://localhost:8080/employee/add?firstName=ivan&lastName=маМин-сибирЯК&salary=25000&departmentId=2
Accept: application/json

### Add Petr Petrov Dprt1
GET http://localhost:8080/employee/add?firstName=Slava&lastName=pETRov&salary=45000&departmentId=2
Accept: application/json

### Add Sidor Sidorov Dprt1
GET http://localhost:8080/employee/add?firstName=SIDOR&lastName=2sidoROV&salary=55000&departmentId=2
Accept: application/json

### Find Sidor Sidorov
GET http://localhost:8080/employee/find?firstName=Sidor&lastName=Sidorov
Accept: application/json

### Set salary - Sidor Sidorov
GET http://localhost:8080/employee/set-salary?firstName=sidor&lastName=sidoRov&salary=55000
Accept: application/json

### Remove by fullname
GET http://localhost:8080/employee/remove?firstName=Sidor&lastName=Sidorov
Accept: application/json